name: CI/CD Workflow

on:
    push

jobs:
    build:
        runs-on: ubuntu-latest

        steps: 
        - uses: actions/checkout@v4
        
        - name: Setup Firefox
          uses: browser-actions/setup-firefox@v1
          
        - name: Set up Python
          uses: actions/setup-python@v5
          with: 
            python-version: '3.11'

        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run Tests
          run: python manage.py test
